language: java

# prevent automatic gradle build
install: true

stages:
  - name: build
  - name: snapshot
    if: branch = master
  - name: example
    if: branch = master
  - name: release
    if: tag =~ ^v\d

before_install:
  - chmod +x gradlew example/gradlew

jobs:
  include:
    - stage: build
      script: ./gradlew build test jar
    - stage: snapshot
      script: ./gradlew uploadArchives -Psnapshot -PmavenPassword=${SNAPSHOT_TOKEN}
    - stage: release
      script: ./gradlew uploadArchives -PmavenPassword=${SNAPSHOT_TOKEN}
    - stage: example
      script: cd example && ./gradlew run
