language: java

# prevent automatic gradle build
install: true

stages:
  - name: build
  - name: snapshot
    if: branch = master
  - name: example
    if: branch = master
  - name: release
    if: tag =~ ^v\d

before_install:
  - chmod +x gradlew example/gradlew

jobs:
  include:
    - stage: pre-conditions
      script: curl https://www.google.com/
    - stage: build
      script: ./gradlew build test jar
    - stage: snapshot
      script: ./gradlew uploadArchives -Psnapshot -PmavenPassword=${SNAPSHOT_TOKEN}
    - stage: release
      script: ./gradlew uploadArchives -PmavenPassword=${SNAPSHOT_TOKEN}
    - stage: example
      script: cd example && ./gradlew run

# maven: mvn deploy -s settings.xml -X -Dsnapshot.pw=${SNAPSHOT_TOKEN}
# settings.xml:
# <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
#   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
#   xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
#   http://maven.apache.org/xsd/settings-1.0.0.xsd">
#   <servers>
#     <server>
#       <id>packagecloud-dled</id>
#       <password>${snapshot.pw}</password>
#     </server>
#   </servers>
# </settings>
